project:
  type: book
  output-dir: _site
  
# netlify deploy --prod --dir=_state  for https://tmd-examine-state.netlify.app/
# netlify deploy --prod --dir=_cd  for https://tmd-examine-cds.netlify.app/

# netlify deploy --prod --dir=_state --site=4842eca7-3a3b-4183-8b73-5635ad95101d
# netlify deploy --prod --dir=_cd --site=573ad544-144b-4535-88cb-f2c41792fe84

format:
  html:
    theme: cosmo
    code-fold: true   

book:
  title: "{{book_title}}"
  date: now
  date-format: "MMM D, YYYY  hh:mm a"
  chapters:
    - index.qmd
    - data_preparation.qmd
    - summary_analysis.qmd
    - individual_reports.qmd

