project:
  type: book
  output-dir: _examine

# https://prerelease.quarto.org/  # quarto documentation at this link

# publishing with netllify cli:
#  open terminal in examine
# quarto render && netlify deploy --prod --dir=_examine

#  quarto render # inspect to be sure it is as desired
#  netlify deploy --prod --dir=_examine

# or step by step
#  netlify deploy # to test it, give _examine as publish directory
#  netlify deploy --prod   # to deploy, give _examine as publish directory

execute:
  eval: true
  echo: true
  output: true
  freeze: false  # auto: during global project renders, re-render only when source changes

book:
  title: "Examine results using area weights"
  subtitle: "Create csv file"
  # author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    # - part: "Examine Congressional Districts"
    #   chapters:
    #     # - cd_overall_documentation.qmd
    #     - cd_get_and_save_selected_ACS_data.qmd
    #     - cd_get_and_save_cd_weights.qmd
    #     - cd_get_tmd_and_summarize_and_save_cd_weighted_results.qmd
    #     - cd_get_and_save_targets.qmd
    #     - cd_combine_data_for_tables.qmd
    #     - cd_comparison_summary.qmd
    - part: "Examine states"
      chapters:
        - state_data_preparation.qmd
        - state_summary_analysis.qmd
        - individual_state_reports.qmd

format:
  html:
    theme: cosmo
    code-fold: true    

editor_options:
  chunk_output_type: console

# R packages using old 209 libxml
#  gt, 


# rendering commands
#   quarto render
#   quarto publish netlify --no-prompt --no-render --no-browser

# possibly use this at start of each doc
# ---
# output: html_document
# editor_options: 
#   chunk_output_type: console
# ---

  
  