project:
  type: book
  output-dir: _web

# https://prerelease.quarto.org/  # quarto documentation at this link


# site info:
  # site ID: 9c6bf4ca-1b88-4735-9c29-ec5a41dab2ef
  # url: https://tmd-areas-prepare-state-targets.netlify.app

# publishing with netlify cli:
#  open terminal in prepare
#  quarto render && netlify deploy --prod --dir=_web

#  quarto render # inspect to be sure it is as desired
#  netlify deploy --prod --dir=_web

# or step by step
#  netlify deploy # to test it, give _examine as publish directory
#  netlify deploy --prod   # to deploy, give _web as publish directory

execute:
  eval: true
  echo: true
  output: true
  freeze: false  # auto: during global project renders, re-render only when source changes

book:
  title: "Develop targets for States"
  subtitle: "Create csv target files for use by area targeting routines"
  # author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - part: "Usage"
      chapters:
        - usage.qmd
    - part: "Get and clean data"
      chapters:
        - download_clean_save_census_state_population_data.qmd
        - download_soi_data.qmd
        - construct_soi_documentation.qmd
        - construct_long_soi_data_file.qmd
    - part: "Create data from which to extract state target files"
      chapters: 
        - create_state_targets_basefile.qmd
        - create_additional_state_targets.qmd
        - combine_base_and_additional_targets.qmd
    - part: "Writing target files"
      chapters: 
        - 50_state_data_underlying_target_files.qmd
  appendices:
  - notes_on_areas_and_targets.qmd
  - SALT_analysis.qmd
        
format:
  html:
    theme: cosmo
    code-fold: true

editor_options:
  chunk_output_type: console
  
# 5 states to do:  NJ, NM, VA, AK, MN  
# also, SC for Jason

# rendering commands
#   quarto render
#   quarto publish netlify --no-prompt --no-render --no-browser

# possibly use this at start of each doc
# ---
# output: html_document
# editor_options: 
#   chunk_output_type: console
# ---

  
  