project:
  type: book
  output-dir: _web

# https://prerelease.quarto.org/  # quarto documentation at this link


# site info:
  # OLD Unique deploy URL:  https://671e13320a7e7cfb68b1ba7d--tmd-areas-prepare-targets.netlify.app
  # url: https://tmd-areas-prepare-state-targets.netlify.app

# publishing with netlify cli:
#  open terminal in prepare
#  quarto render && netlify deploy --prod --dir=_web

#  quarto render # inspect to be sure it is as desired
#  netlify deploy --prod --dir=_web

# or step by step
#  netlify deploy # to test it, give _examine as publish directory
#  netlify deploy --prod   # to deploy, give _web as publish directory

execute:
  eval: true
  echo: true
  output: true
  freeze: false  # auto: during global project renders, re-render only when source changes

book:
  title: "Develop targets for States"
  subtitle: "Create csv target files for use by area targeting routines"
  # author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - part: "Usage"
      chapters:
        - usage.qmd
    - part: "IRS SOI State data"
      chapters:
        - download_soi_data.qmd
        - construct_soi_documentation.qmd
        - construct_long_soi_data_file.qmd
    - part: "SALT analysis"
      chapters:
        - developing_SALT_targets.qmd
        # - explore_soi_data.qmd
        # old files maybe use as base for new work
        # - cd_download_and_clean_census_population_data.qmd        
        # - cd_create_variable_mapping.qmd
        # - cd_compare_us_totals_tmd_vs_irs_published.qmd
        # - cd_enhance_basefile_with_special_targets.qmd
  # appendices:
  #   - cd_issues_and_TODOs.qmd  
  #   - cd_IRS_documentation.qmd
        
format:
  html:
    theme: cosmo
    code-fold: true

editor_options:
  chunk_output_type: console
  
# 5 states to do:  NJ, NM, VA, AK, MN  

# rendering commands
#   quarto render
#   quarto publish netlify --no-prompt --no-render --no-browser

# possibly use this at start of each doc
# ---
# output: html_document
# editor_options: 
#   chunk_output_type: console
# ---

  
  